apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtap-test
  labels:
    "pipelines.openshift.io/used-by": ""
    "pipelines.openshift.io/runtime": ""
    "pipelines.openshift.io/strategy": ""
spec:
  params:
    - description: 'Source Repository URL'
      name: git-url
      type: string
    - description: 'Revision of the Source Repository'
      name: revision
      type: string
      default: ""
    - description: 'Fully Qualified Output Image'
      name: output-image
      type: string
    - description: Path to the source code of an application's component from where to build image.
      name: path-context
      type: string
      default: .
    - description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
      default: Dockerfile
    - description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      default: ""
    - name: build-source-image
      description: Build a source image.
      type: string
      default: "false"
    - name: skip-push
      default: "false"
      description: Skip pushing the image to the container registry.
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "$(params.revision)"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: build-container
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: SKIP_PUSH
          value: $(params.skip-push)
      taskRef:
        name: buildah-rhtap
      workspaces:
        - name: source
          workspace: workspace
  #   - name: sbom-json-check
  #     runAfter:
  #       - build-container
  #     taskRef:
  #       name: sbom-json-check
  #     params:
  #     - name: IMAGE_URL
  #       value: $(tasks.build-container.results.IMAGE_URL)
  #     - name: IMAGE_DIGEST
  #       value: $(tasks.build-container.results.IMAGE_DIGEST)
  # finally:
  #   - name: show-sbom
  #     taskRef:
  #       name: show-sbom
  #     params:
  #     - name: IMAGE_URL
  #       value: $(tasks.build-container.results.IMAGE_URL)
  results:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: SBOM_BLOB_URL
      value: "$(tasks.build-container.results.SBOM_BLOB_URL)"
  workspaces:
    - name: workspace
    - name: git-auth
      optional: true
